apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: insurance_state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6381
  - name: redisPassword
    value: ""
  - name: queryIndexes
    value: |
      [
        {
          "name": "insuranceIndex",
          "indexes": [
            {
              "key": "userName",
              "type": "TEXT"
            },
            {
              "key": "insuranceType",
              "type": "NUMERIC"
            },
            {
              "key": "id",
              "type": "TEXT"
            }
          ]
        }
      ]
